### ISSUE TITLE
Class not found co.elastic.apm.api.Span when starting application in Anypoint Studio

### ISSUE THREAD

**Issue by iaregalado** [michaelhyatt/elastic-apm-mule3-agent#15]
After configuring a project following the instructions from the [blog post](https://www.elastic.co/blog/observability-of-mulesoft-using-elastic-apm-to-monitor-mule-flows), starting up the application always results in that Class not being found.  Did I miss something in the guide?

[log.log](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/3249501/log.log)

**Comment by michaelhyatt** [comment]
Your project setup seems to be missing the APM jars. It should load the following jars:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ New app 'test385'                                        +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2019-06-01 08:51:55,017 [main] org.mule.module.launcher.MuleApplicationClassLoader: [test385] Loading the following jars:
=============================
file:/Users/axolotl/work/elastic/AnypointStudio/workspace/.mule/apps/test385/lib/elastic-apm-agent-1.6.0.jar
file:/Users/axolotl/work/elastic/AnypointStudio/workspace/.mule/apps/test385/lib/apm-agent-attach-1.6.0.jar
file:/Users/axolotl/work/elastic/AnypointStudio/workspace/.mule/apps/test385/lib/apm-mule3-agent-1.6.2.jar
file:/Users/axolotl/work/elastic/AnypointStudio/workspace/.mule/apps/test385/lib/apm-agent-api-1.6.0.jar
```

In your case, only `apm-mule3-agent-1.6.2.jar` is there:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ New app 'elastic_search'                                 +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2019-05-31 10:36:15,665 [main] org.mule.module.launcher.MuleApplicationClassLoader: [elastic_search] Loading the following jars:
=============================
...
file:/Users/ivan_regalado/AnypointStudio/workspace/.mule/apps/elastic_search/lib/apm-mule3-agent-1.6.2.jar
...
=============================
```

Hence is the problem with the missing classes. So, it looks like a project setup issue. Have a look at the attached sample project I tested the loading sequence and Mule 3.8.5 with.
[test385.zip](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/3243091/test385.zip)

**Comment by iaregalado** [comment]
Thanks @michaelhyatt - I'll take a look and add the necessary jar's.

**Comment by iaregalado** [comment]
Hey @michaelhyatt - so I've got it all up and running now, and with your test app I can't see any traces or transactions in Kibana.  I am able to see the service show up, but no content within it either.

![image](https://user-images.githubusercontent.com/10901040/58822873-51585e80-85ed-11e9-8b64-5d5a7ed74555.png)

![image](https://user-images.githubusercontent.com/10901040/58822885-59180300-85ed-11e9-8580-691cb3c3448a.png)

Any ideas?

[test385.log](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/3248804/test385.log)

**Comment by iaregalado** [comment]
Side note, I just started a free trial of Elastic cloud, and I'm running into the same issue there.

**Comment by michaelhyatt** [comment]
If you can see the service name in Kibana, then your Mule agent is communicating with the APM server and Elastic cluster. Did you try to run some transactions through Mule?

`curl -v http://localhost:8081`

**Comment by iaregalado** [comment]
Hey Michael,

I did run transactions through the test app (a for loop like you did in your video):

```
INFO  2019-06-03 10:46:25,507 [[test385].HTTP_Listener_Configuration.worker.01] org.mule.api.processor.LoggerMessageProcessor: this is a test
```
Yet still nothing in Kibana, other than the service name.

**Comment by michaelhyatt** [comment]
Here is another sample project that works with Mule 3.9.0 
[test390.zip](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/3250053/test390.zip)

Let me look into why it is not working with Mule 3.8.5. Meanwhile, can you use to 3.9.0?

**Comment by michaelhyatt** [comment]
MuleSoft changed the notification API going from 3.8 to 3.9 adding a new event `MessageProcessorNotification.MESSAGE_PROCESSOR_PRE_INVOKE_ORIGINAL_EVENT` in 3.9 that wasn't there in 3.8. The agent relies on this event to close Spans corresponding to MessageProcessors, or flow activities. The current version of the agent `v1.6.2` won't work with Mule 3.8.5

**Comment by iaregalado** [comment]
Hey @michaelhyatt thanks for looking into this; I ran your sample 390 project and yep, I can now see traces in Kibana as I execute transactions.  Will keep an eye out for support for Mule 3.8.5 enhancement.  Thanks again!

**Comment by michaelhyatt** [comment]
@iaregalado I added support for Mule 3.8 projects and quickly tested it. You will need a different jar and Maven dependency. See the updated README and release 1.6.3

**Comment by iaregalado** [comment]
Thanks @michaelhyatt - I've updated my 385test project with the new jar and now content is showing up in the service:

![image](https://user-images.githubusercontent.com/10901040/58930605-f029ab80-8710-11e9-8dbb-312aec5f7722.png)
