### ISSUE TITLE
Transactions not appearing in Kibana for Mule 3.9.3 EE

### ISSUE THREAD

**Issue by AdamLounsbury** [michaelhyatt/elastic-apm-mule3-agent#18]
I downloaded your example project **test390** (Mule 3.9.0 EE runtime), added a few extra components for testing, and had no issues running it and viewing its results in Kibana. However, switching to runtime 3.9.3 EE results in no _transactions_ appearing in Kibana (the service does appear though).

Comparing the stack traces of 3.9.0 vs 3.9.3, I can notice a few things, namely that specific increment/decrement references are occurring in different areas (or not occurring at all). I've attached them for reference here. If you have any ideas why this is occurring and have an idea for a fix, I'd be grateful. This tool is amazing, but I'm working with 3.9.3 on a project that I'd like to use this on!

Stack trace from 3.9.3 app (failure - no transactions appear in Kibana):
[mule393failure.txt](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/3473552/mule393failure.txt)

Stack trace from 3.9.0 app (successful - can view transactions in Kibana):
[mule390success.txt](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/3473553/mule390success.txt)

Would you mind taking a look/advising on if 3.9.3 support is likely/possible? Thank you!

**Comment by michaelhyatt** [comment]
@AdamLounsbury thanks for reporting it. I confirmed that Mule 3.9.3 doesn't work with Mule APM agent version 1.7.0. I was working on upgrading the Mule agent to version 1.8.0 and Mule 3.9.3 seems to be working with this release. Can you please check out the newer version of the Mule APM agent that I added to Releases section? Here is also a sample project that works with Mule 3.9.3 and Mule APM agent version 1.8.0.
[test393.zip](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/3475130/test393.zip)

**Comment by michaelhyatt** [comment]
@AdamLounsbury ^^ Let me know if you had a chance to check the new version out.

**Comment by AdamLounsbury** [comment]
Hi @michaelhyatt apologies for the delay! It's been a busy week. I just got around to testing it and it's working fine now! Thanks so much for the quick fix. No issues anymore :)
