### ISSUE TITLE
Error running example-app in anypoint studio (Mule Runtime 3.9.0)

### ISSUE THREAD

**Issue by au-zl** [michaelhyatt/elastic-apm-mule3-agent#20]
Example fails to run during deployment with java.lang.ClassNotFoundException: co.elastic.apm.api.Span

**Comment by AdamLounsbury** [comment]
I encountered something similar initially during setup, so perhaps you're suffering from the same thing I did.

Check your POM/referenced libraries in the project and make sure that the follow entries are present:

apm-mule3-agent version 1.8.0 (apm-agent-api-1.8.0.jar)
apm-agent-attach version 1.8.0 (apm-agent-attach-1.8.0.jar)
apm-agent-api version 1.8.0 (apm-mule3-agent-1.8.0.jar)
elastic-apm-agent version 1.8.0 (elastic-apm-agent-1.8.0.jar)

If those four things aren't present in your referenced libraries (and/or aren't present in your POM), then that's likely why you're seeing that.

**Comment by yukisan** [comment]
> I encountered something similar initially during setup, so perhaps you're suffering from the same thing I did.
> 
> Check your POM/referenced libraries in the project and make sure that the follow entries are present:
> 
> apm-mule3-agent version 1.8.0 (apm-agent-api-1.8.0.jar)
> apm-agent-attach version 1.8.0 (apm-agent-attach-1.8.0.jar)
> apm-agent-api version 1.8.0 (apm-mule3-agent-1.8.0.jar)
> elastic-apm-agent version 1.8.0 (elastic-apm-agent-1.8.0.jar)
> 
> If those four things aren't present in your referenced libraries (and/or aren't present in your POM), then that's likely why you're seeing that.

Thanks Adam, do you know where can we download the other 1.8 files? elastic.co points me to maven central and the only version available for download now are version 1.10.

**Comment by michaelhyatt** [comment]
@yukisan version 1.10 should work as well.
