### ISSUE TITLE
addLabel() on span and transaction not work

### ISSUE THREAD

**Issue by sobelfallcayor** [michaelhyatt/elastic-apm-mule3-agent#21]
Hi,
By test this api, i see that addLabel for span and transaction not works.
My code is :
`Transaction transaction = ElasticApm.currentTransaction();
  Span span = ElasticApm.currentSpan();
	transaction.addLabel("label1", "start processing");
			span.addLabel("compteur", 1234);`
	
I need to add custom informations in each mule step (Span). See attachment.

Thanks for.
![image](https://user-images.githubusercontent.com/2944063/67413509-d3531f00-f5b0-11e9-83cd-f87d01639a64.png)

**Comment by michaelhyatt** [comment]
Hi,

Elastic Java APM agent API won't be able to attach labels to the current transaction. I can suggest two options to annotate transactions with custom values:

1. You can populate a label through a flowVar https://github.com/michaelhyatt/elastic-apm-mule3-agent#capturing-flowvar-values-as-span-tags
2. You can create a step that will be captured as `Span` in a transaction. A DEBUG Logger flow step, for example, can be used with static labels, such as "Start Processing".

Please let me know if I am missing something.

**Comment by sobelfallcayor** [comment]
maybe i don't really understand but what you mean by "**_Elastic Java APM agent API won't be able to attach labels to the current transaction_**".
Related to documentation : https://www.elastic.co/guide/en/apm/agent/java/1.x/public-api.html#api-transaction-add-tag
I can call the current transaction and use api method for what i need to do (include add label and others).

In other side, when using this project "elastic-apm-mule3-agent", i see that when calling current transaction, i have a "noop span" that means (related to doc) : 
"If there is no current span, this method will return a noop span, which means that you never have to check for null values."

By source code (co.elastic.apm.mule.utils.SpanStore), i see you only start transaction for the first encountered flow and store it as a topLevelTransaction. When using this, i can add label and other. (I dont really like the way to patch the SpanStore class).

Otherwise, for your suggestion : 
 1 : look like not what a need : i need to have a control on transaction and edit name to inject dynamic string and add custom elements....

 2 : In my usecase, i have a java code in each step. I need a danamic label for that.

So to solve it, i use solution below : 

`public class SpanStore {

	private Map<String, Map<Optional<MessageProcessor>, Span>> map = new ConcurrentHashMap<>();
	public   Span topLevelSpanTransaction;
	public   Span currentSpanTransaction;`

`public void storeTransactionOrSpan(String key, ServerNotification notification, Span span) {

		Optional<MessageProcessor> key2 = getKey2(notification);

		Map<Optional<MessageProcessor>, Span> innerMap = map.get(key);
		//notification.getResourceIdentifier();
		if (innerMap == null)
		{
			innerMap = new ConcurrentHashMap<>();
			span.setName(notification.getResourceIdentifier()+"step-1");
			topLevelSpanTransaction = span;
		}

		currentSpanTransaction = span;
		innerMap.put(key2, span);
		map.put(key, innerMap);
	}`

`
@Autowired
	private SpanStore spanStore;
	
	@Override
	public Object onCall(MuleEventContext eventContext) throws Exception {
		
		spanStore.topLevelSpanTransaction.addLabel("JavaTraitement_1", "JavaTraitement1_value");
		spanStore.currentSpanTransaction.setName("JavaTraitement_1-step-alpha");
		
		
		 Span span = spanStore.topLevelSpanTransaction.startSpan();
		try {
		    span.setName("SELECT FROM customer");

		} catch (Exception e) {
		    span.captureException(e);
		    throw e;
		} finally {
		    span.end();
		}`


Now i can use a variable to adress the need of tracing.....
Maybe that is not a good idea.

**Comment by michaelhyatt** [comment]
Hey, 

A better idea would be to add a public method to SpanStore class to retrieve the current Span without removing it from the stack, something like that:

```
	public Span peekTransactionOrSpan(String key, ServerNotification notification) {

		Optional<MessageProcessor> key2 = getKey2(notification);

		Map<Optional<MessageProcessor>, Span> stack = map.get(key);
		Span span = stack.peek(key2);
		
		return span;
	}
```

try it and create a pull request if it works for you.

**Comment by michaelhyatt** [comment]
@fallphenix I didn't hear from you if it resolved the issue.

**Comment by michaelhyatt** [comment]
provided a workaround, closing for now. Re-open if the change is needed.
