### ISSUE TITLE
APM will not send data to ES

### ISSUE THREAD

**Issue by epaulferrer** [michaelhyatt/elastic-apm-mule3-agent#22]
Hi @michaelhyatt ,

this is related to this issue  
[https://github.com/michaelhyatt/elastic-apm-mule3-agent/issues/11](url)

 APM will not send data to ES unless properties are manually specified in the cloudHub properties settings. 

its not reading it from the mule.properties file. 

![image](https://user-images.githubusercontent.com/12424199/74297947-59bf8680-4d83-11ea-9d36-9c3a7372eec8.png)

**Comment by michaelhyatt** [comment]
Hey, is it the default CloudHub behaviour where the properties file values are always replaced with the ones updated in CloudHub?

https://docs.mulesoft.com/runtime-manager/deploying-to-cloudhub#overriding-properties-in-cloudhub-vs-on-premises-mule

**Comment by michaelhyatt** [comment]
@epaulferrer ^^ pinging you if it got resolved

**Comment by michaelhyatt** [comment]
closing it for now
