### ISSUE TITLE
Install Jar and run without Maven or building from Mule from pom?

### ISSUE THREAD

**Issue by kanekennedy** [michaelhyatt/elastic-apm-mule3-agent#23]
Hi Michael,

I am not a developer, lets start with that...

Is it feasable (possible) to install the jar and have Mule3.8.0 start it as an application similar to enabling the Jolokia endpoint jmx export?  I fudged my round getting that working but your agent looks like it would give a far richer level of information over what the jmx export is giving us.

**Comment by michaelhyatt** [comment]
It should be possible in theory to add the jar as a project dependency in Eclipse (studio), but I never tried it. Give it a go and let me know the result, if possible.

I tested the code with 3.8.5, not sure if it will work with 3.8.0. Another thing to test.

JMX metrics support was added to Elastic APM agent in version 1.11.0 and I am using version 1.8.0. Do you want to collect Mule JMX metrics using the APM agent? If yes, I will look into upgrading the agent to the latest and greatest version of the APM agent soon.

**Comment by kanekennedy** [comment]
Thanks for the response Michael,

We are stuck for the moment on 3.8.0 (unless you can advise if there any code breaking changes) as none of us with time have the ability to rewite to another version.

Upgrading the agent to pull jmx as well would be awesome as I assume then we would not need to also deploy the Jolokia endpoint.

**Comment by michaelhyatt** [comment]
hey @kanekennedy , got some good news for you. You won't need jolokia to pull JMX metrics from Mule JVM. You can use the agent for it.

Attaching the jars works without having to mavenize your project. I tested the 3.8 agent and it seems to be working with Mule 3.8.0 EE. I also updated the agent with the new Java APM agent v1.15.0 that (among other things) supports JMX MBeans metrics collection. I am in the process of merging the pull request, but in the meanwhile, I am attaching the jars and the sample project. Let me know how it goes.

[Archive.zip](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/4604889/Archive.zip)

**Comment by michaelhyatt** [comment]
hope the solution works, closing it for now.
