### ISSUE TITLE
Support for ELASTIC_APM_ENABLE_LOG_CORRELATION - log4j2

### ISSUE THREAD

**Issue by stuart-frew** [michaelhyatt/elastic-apm-mule3-agent#24]
I rebuild library with v1.15 of the apm library, 1.10.8 of version.byte-buddy.

The env variable ELASTIC_APM_ENABLE_LOG_CORRELATION was set to true.

However the contextMap of the log4j2 log did not contain either the trace.id or transaction.id
Our own information in the context map appears

OS windows 2016
AdoptOpenJava 1.8
Mule 3.8.5

**Comment by michaelhyatt** [comment]
I think MDC uses ThreadLocal store for context storing and Mule 3.x uses different threads to execute the thread, so I don't think MDC will work here... But I may be wrong. Happy to discuss and be educated if I misunderstand it. 

It can be a really cool feature to get logs and APM traces correlated in Elastic out of the box.

**Comment by stuart-frew** [comment]
We are experimenting with logging a custom correlation ID using Thread Context.
A simple method is called during the main flow that contains the `apikit:router`.

It only does a `ThreadContext.put("CorrelationId`, id)` using data from a header.

The Log4j2 `PatternLayout` has a `%X{CorrelationId}` in its pattern definition.

This seems to work.

The hope is that we can get transaction and trace Id logging for free and join the APM and application logs.

**Comment by michaelhyatt** [comment]
Looked into it a bit more and it seems that MDC is not populated if the Elastic APM agent instrumentation is off. I will need to populate the context in my wrapper code, give me few days to get to it and test it properly.

**Comment by michaelhyatt** [comment]
@estergum check out the latest release v1.15.1

You should be able now see `trace.id` and `transaction.id` populated in MDC traceContext. Use `%X{trace.id}` and `%X{transaction.id}` in your pattern layout to retrieve them.

**Comment by stuart-frew** [comment]
It works, excellent!

Thanks.

**Comment by michaelhyatt** [comment]
Awesome, closing this.
