### ISSUE TITLE
Question about configuring a Mule with a  Domain project (3.8.5)

### ISSUE THREAD

**Issue by stuartfrewcl** [michaelhyatt/elastic-apm-mule3-agent#27]
When configuring a mule service with multiple apps under a domain project is it expected that setting the bean in the domain is enough, or does the bean need to be added to the applications as well.

My experiments implies the bean is required in both domain and application but the documentation suggests setting it in the domain project is enough.

**Comment by michaelhyatt** [comment]
@stuartfrewcl domain-level setting should be sufficient. Check out the [domain project example](https://github.com/michaelhyatt/elastic-apm-mule3-agent/tree/master/example-domain-app).

**Comment by stuartfrewcl** [comment]
It appears to be a side effect of having `apikit` in the domain application.
I'll raise a seperate ticket that is focused on this.
