### ISSUE TITLE
Containers for components 1/2 wont start

### ISSUE THREAD

**Issue by aparasxidis** [michaelhyatt/elastic-apm-mule3-agent#29]
Im following your guide, elasticsearch, kibana, apm and loadgen are running, but the components are giving me this error when I check logs

```
: not foundm-server.sh: 2: wait-for-apm-server.sh:
wait-for-apm-server.sh: 3: set: Illegal option -
```

I've searched and is about the script command, I try some configurations with bash instead of sh, but it gives me different errors:

```
wait-for-apm-server.sh: line 2: $'\r': command not found
: invalid optionver.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
wait-for-apm-server.sh: line 4: $'\r': command not found
wait-for-apm-server.sh: line 6: $'shift\r': command not found
wait-for-apm-server.sh: line 8: $'shift\r': command not found
wait-for-apm-server.sh: line 10: $'\r': command not found
wait-for-apm-server.sh: line 23: syntax error: unexpected end of file
```

**Comment by michaelhyatt** [comment]
Hey, sorry for the delay in response, pretty busy lately. I think your shell script was saved in Windows mode with `\r` at the end of lines, as described here:
https://stackoverflow.com/questions/35352955/set-illegal-option-on-one-host-but-not-the-other

Can you try to change the format to Unix to get rid of <CR> and save it?

**Comment by michaelhyatt** [comment]
Hope the fix works for you, please re-open it if you need more help.
