### ISSUE TITLE
Transactions not appearing in Kibana for Mule 3.9.4 EE

### ISSUE THREAD

**Issue by jpandher1991** [michaelhyatt/elastic-apm-mule3-agent#31]
Hi 

Transactions are not visible in Kibana when we upgraded to 3.9.4 from 3.9.0.i was working fine with 3.9.0.we are using Elastic APM 1.8.0
[log.txt](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/4853367/log.txt)

**Comment by michaelhyatt** [comment]
hey, is it the same as #30 ?

**Comment by abhishekksingh2019** [comment]
Yes it is same. We are on the same team :)

**Comment by michaelhyatt** [comment]
no probs, in case it is related to domains and API kit, check out the patch I referenced in #28 

It is a newer version and has fixes compared to 1.8.0.
