### ISSUE TITLE
Elastic APM 7.8+ Service Map Integration

### ISSUE THREAD

**Issue by tomqwu** [michaelhyatt/elastic-apm-mule3-agent#32]
with 1.13+ for Java agent plus the new Elastic APM 7.8, https://www.elastic.co/guide/en/kibana/current/service-maps.html

**Comment by michaelhyatt** [comment]
@tomqwu I noticed the issue with the Java agent 1.17.0 and Stack v 7.8.0, I want to re-test it with 7.8.1 because the same setup worked with 7.7. So, please stay tuned.

**Comment by michaelhyatt** [comment]
@tomqwu found the issue and a workaround. If you select Integrations dropdown in APM UI on a service page and enable machine learning, it will make service maps appear.

**Comment by michaelhyatt** [comment]
Closing for now, please reopen if it is still an issue.
