### ISSUE TITLE
elastic-apm-mue 3 with different entry point

### ISSUE THREAD

**Issue by ghost** [michaelhyatt/elastic-apm-mule3-agent#34]
Hello Michael,
I followed all the steps of your project with a single HTTP entry point as you did here (elastic.apm.mule.capture_input_properties_regex = http _ (. *)) And it works great.
Currently the problem I have is that in my project I have several entry points like QUARTZ, ActiveMQ consumer, Java class and I don't know how to instantiate them as entry point.
I tried this (elastic.apm.mule.capture_input_properties_regex = quartz _ (. *)) But it doesn't work.
Thank you for your assistance.

cordially
[mule.zip](https://github.com/michaelhyatt/elastic-apm-mule3-agent/files/4987251/mule.zip)

**Comment by michaelhyatt** [comment]
Are you seeing the transactions corresponding to the top level flows with Quartz and other flow starters?

The property that you mentioned is only applicable to capturing the properties of these flows, not creating the flow transactions.

**Comment by ghost** [comment]
@Michaelhyatt I don't understand what you mean here "The property that you mentioned is only applicable to capturing the properties of these flows, not creating the flow transactions."
My problem is instead of:
- elastic.apm.mule.capture_input_properties_regex = http_ (. *)
Do I have to put:
- elastic.apm.mule.capture_input_properties_regex = quartz_ (. *)
- elastic.apm.mule.capture_input_properties_regex = jms_ (. *)
What property should I put to capture Quartz or ActiveMQ

**Comment by michaelhyatt** [comment]
Ah, got it. This property should contain a regex that captures all the
properties you are after, like this:

elastic.apm.mule.capture_input_properties_regex = http_(. *)|quartz_(.
*)|jms_(. *)

Does it make sense?

**Comment by ghost** [comment]
Hello Michael,
Sorry for the delay in my response I had taken a few days.
But I tested what you suggested to me and it's okay it's working normally now
Thanks again for your assistance
cordially

**Comment by michaelhyatt** [comment]
good to hear.
