### ISSUE TITLE
License of elastic-apm-mule3-agent

### ISSUE THREAD

**Issue by zalintyre** [michaelhyatt/elastic-apm-mule3-agent#37]
Hello,

this GitHub project doesn't supply a LICENSE file. For us it is unclear if we can use the agent in our project. Is it open source? What license applies to this project?

Kind regards
Franz

**Comment by michaelhyatt** [comment]
Great point, thanks for raising. Added Apache 2.0 license, hope it works
for you.

**Comment by michaelhyatt** [comment]
added the license file, hope it is resolved.

**Comment by zalintyre** [comment]
Thank you very much!
