### ISSUE TITLE
Support for java agent 1.5

### ISSUE THREAD

**Issue by michaelhyatt** [michaelhyatt/elastic-apm-mule3-agent#8]
Migration to use Elastic Java APM agent 1.5

**Comment by dspasojevic** [comment]
I'm interested in contributing a PR to support this. Are there any pointers that you could provide?

**Comment by michaelhyatt** [comment]
@dspasojevic Thanks for trying the agent out and willing to help. I just finished updating the `master` to use agent version 1.6.0 with some neat improvements around configuration. Check out the master, I will tag a release at a later stage after I test it a bit more.
